[package]
name = "ah_render"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "23.0.0"
bevy_ecs = "0.15.0-rc.3"
bevy_ecs_macros = "0.15.0-rc.3"
winit = "0.30.5"
image = "0.25.5"
glam ="0.29.2"
bytemuck = "1.19.0"