[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.30.9", features = ["rwh_05"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
bevy_ecs = "0.15.2"
renderer ={path = "../renderer"}
